spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docker?currentSchema=public
    username: ${SPRING_DATASOURCE_USERNAME:sokmean}
    password: 12345
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: debug
